name: Android CI

on:
  push:
    branches: [ "Part3_halfway" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Unit Test
      run: ./gradlew test

    # run emulator for UI Test
    - name: Start emulator
      run: 
          emulator -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82

    - name: Run UI Test
      run: ./gradlew connectedAndroidTest

    - name: Stop emulator
      run: adb -s emulator -5554 emu kill
